# Generated by Django 4.2.2 on 2025-06-18 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArtGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist", models.CharField(max_length=255)),
                ("image", models.ImageField(upload_to="media/gallery")),
                ("title", models.CharField(max_length=255)),
                ("content_view", models.IntegerField(default=1)),
                ("status", models.BooleanField(default=False)),
                ("poblished_date", models.DateTimeField(null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["created_date"],
            },
        ),
    ]
