# Generated by Django 4.2.2 on 2025-05-21 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Artist", "0002_comments"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comments",
        ),
    ]
