# Generated by Django 4.2.2 on 2025-06-06 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Artist", "0004_post_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="tags",
        ),
    ]
