# Generated by Django 4.2.2 on 2025-06-09 15:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("Artist", "0005_remove_post_tags"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="Artist",
        ),
    ]
