# Generated by Django 4.2.2 on 2025-07-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Artist", "0006_rename_post_artist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artist",
            name="image",
            field=models.ImageField(
                default="media/Artist/default.jpg", upload_to="Artist"
            ),
        ),
    ]
