# Generated by Django 4.2.2 on 2025-07-29 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Artwork", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artwork",
            name="image",
            field=models.ImageField(default="media/Art/default.jpg", upload_to="Art"),
        ),
    ]
